-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 23:26:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eh9qgjoxmmy0l0q9
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eh9qgjoxmmy0l0q9
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eh9qgjoxmmy0l0q9` DEFAULT CHARACTER SET utf8 ;
USE `eh9qgjoxmmy0l0q9` ;

-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`estado_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`estado_usuario` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `descripcionEstado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `descripcionRol` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `password` VARCHAR(500) NULL,
  `idEstado` INT NOT NULL,
  `idRol` INT NOT NULL,
  `activo` TINYINT NULL,
  `_token` VARCHAR(256) NULL,
  `remebmer_token` VARCHAR(256) NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_estado1_idx` (`idEstado` ASC),
  INDEX `fk_rol1_idx` (`idRol` ASC),
  CONSTRAINT `fk_estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`estado_usuario` (`idEstado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rol1`
    FOREIGN KEY (`idRol`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`rol` (`idRol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `imgPerfilURL` VARCHAR(45) NULL,
  `imgPortadaURL` VARCHAR(45) NULL,
  `descripcionPerfil` BLOB NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPerfil`),
  INDEX `fk_usuario6_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_usuario6`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`estado_publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`estado_publicacion` (
  `idEstadoPublicacion` INT NOT NULL AUTO_INCREMENT,
  `descripcionEstado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoPublicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `contenido` BLOB NULL,
  `activo` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `cant_comentarios` INT NULL,
  `visitas` INT NULL,
  `idUsuario` INT NOT NULL,
  `idEstadoPublicacion` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idPost`),
  INDEX `fk_usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_estadoPublicacion1_idx` (`idEstadoPublicacion` ASC),
  CONSTRAINT `fk_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estadoPublicacion1`
    FOREIGN KEY (`idEstadoPublicacion`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`estado_publicacion` (`idEstadoPublicacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `contenido` BLOB NULL,
  `created_at` TIMESTAMP NULL,
  `idPost` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idEstadoPublicacion` INT NOT NULL,
  `activo` TINYINT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_post1_idx` (`idPost` ASC),
  INDEX `fk_usuario2_idx` (`idUsuario` ASC),
  INDEX `fk_estadoPublicacion2_idx` (`idEstadoPublicacion` ASC),
  CONSTRAINT `fk_post1`
    FOREIGN KEY (`idPost`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`post` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario2`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estadoPublicacion2`
    FOREIGN KEY (`idEstadoPublicacion`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`estado_publicacion` (`idEstadoPublicacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`valoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`valoracion` (
  `idValoracion` INT NOT NULL AUTO_INCREMENT,
  `descripcionValoracion` VARCHAR(45) NULL,
  PRIMARY KEY (`idValoracion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`valoracion_comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`valoracion_comentario` (
  `idValoracion` INT NOT NULL,
  `cantidad` INT NULL,
  `idComentario` INT NOT NULL,
  PRIMARY KEY (`idValoracion`, `idComentario`),
  INDEX `fk_valoracion3_idx` (`idValoracion` ASC),
  INDEX `fk_comentario2_idx` (`idComentario` ASC),
  CONSTRAINT `fk_valoracion3`
    FOREIGN KEY (`idValoracion`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`valoracion` (`idValoracion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comentario2`
    FOREIGN KEY (`idComentario`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`comentario` (`idComentario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`valoracion_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`valoracion_post` (
  `idValoracion` INT NOT NULL,
  `idPost` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idValoracion`, `idPost`),
  INDEX `fk_post3_idx` (`idPost` ASC),
  INDEX `fk_valoracion4_idx` (`idValoracion` ASC),
  CONSTRAINT `fk_valoracion4`
    FOREIGN KEY (`idValoracion`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`valoracion` (`idValoracion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post3`
    FOREIGN KEY (`idPost`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`post` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`valoracion_comentario_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`valoracion_comentario_usuario` (
  `idValoracion` INT NOT NULL,
  `idComentario` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idValoracion`, `idComentario`, `idUsuario`),
  INDEX `fk_usuario3_idx` (`idUsuario` ASC),
  INDEX `fk_valoracionComentario1_idx` (`idValoracion` ASC, `idComentario` ASC),
  CONSTRAINT `fk_valoracionComentario1`
    FOREIGN KEY (`idValoracion` , `idComentario`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`valoracion_comentario` (`idValoracion` , `idComentario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario3`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`valoracion_post_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`valoracion_post_usuario` (
  `idValoracion` INT NOT NULL,
  `idPost` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idValoracion`, `idPost`, `idUsuario`),
  INDEX `fk_usuario4_idx` (`idUsuario` ASC),
  INDEX `fk_valoracionPost1_idx` (`idValoracion` ASC, `idPost` ASC),
  CONSTRAINT `fk_valoracionPost1`
    FOREIGN KEY (`idValoracion` , `idPost`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`valoracion_post` (`idValoracion` , `idPost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario4`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`notificacion` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idNotificacion`),
  INDEX `fk_usuario5_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_usuario5`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`notificacion_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`notificacion_post` (
  `idNotificacion` INT NOT NULL,
  `idPost` INT NOT NULL,
  PRIMARY KEY (`idNotificacion`, `idPost`),
  INDEX `fk_post2_idx` (`idPost` ASC),
  CONSTRAINT `fk_notificacion1`
    FOREIGN KEY (`idNotificacion`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`notificacion` (`idNotificacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post2`
    FOREIGN KEY (`idPost`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`post` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eh9qgjoxmmy0l0q9`.`notificacion_comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eh9qgjoxmmy0l0q9`.`notificacion_comentario` (
  `idComentario` INT NOT NULL,
  `idNotificacion` INT NOT NULL,
  PRIMARY KEY (`idComentario`, `idNotificacion`),
  INDEX `fk_notificacion2_idx` (`idNotificacion` ASC),
  CONSTRAINT `fk_comentario1`
    FOREIGN KEY (`idComentario`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`comentario` (`idComentario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notificacion2`
    FOREIGN KEY (`idNotificacion`)
    REFERENCES `eh9qgjoxmmy0l0q9`.`notificacion` (`idNotificacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
