-- MySQL Script generated by MySQL Workbench
-- Mon Oct 24 15:49:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema foroFullstack
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema foroFullstack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foroFullstack` DEFAULT CHARACTER SET utf8 ;
USE `foroFullstack` ;

-- -----------------------------------------------------
-- Table `foroFullstack`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`perfil` (
  `idPerfil` INT NOT NULL,
  `imgPerfilURL` VARCHAR(45) NULL,
  `imgPortadaURL` VARCHAR(45) NULL,
  `descripcionPerfil` BLOB NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`estadoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`estadoUsuario` (
  `idEstado` INT NOT NULL,
  `descripcionEstado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`rol` (
  `idRol` INT ZEROFILL NOT NULL,
  `descripcionRol` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`usuario` (
  `idUsuario` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `password` VARCHAR(500) NULL,
  `idPerfil` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `idEstado` INT NOT NULL,
  `idRol` INT NOT NULL,
  `activo` TINYINT NULL,
  `colUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_perfil_idx` (`idPerfil` ASC) VISIBLE,
  INDEX `fk_estado1_idx` (`idEstado` ASC) VISIBLE,
  INDEX `fk_rol1_idx` (`idRol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `foroFullstack`.`perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `foroFullstack`.`estadoUsuario` (`idEstado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rol1`
    FOREIGN KEY (`idRol`)
    REFERENCES `foroFullstack`.`rol` (`idRol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`estadoPublicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`estadoPublicacion` (
  `idEstadoPublicacion` INT NOT NULL,
  `contenido` BLOB NULL,
  PRIMARY KEY (`idEstadoPublicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`post` (
  `idPost` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `contenido` BLOB NULL,
  `activo` TINYINT NULL,
  `fechaCreacion` DATE NULL,
  `cant_comentarios` INT NULL,
  `visitas` INT NULL,
  `idUsuario` INT NOT NULL,
  `idEstadoPublicacion` INT NOT NULL,
  PRIMARY KEY (`idPost`),
  INDEX `fk_usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_estadoPublicacion1_idx` (`idEstadoPublicacion` ASC) VISIBLE,
  CONSTRAINT `fk_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `foroFullstack`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estadoPublicacion1`
    FOREIGN KEY (`idEstadoPublicacion`)
    REFERENCES `foroFullstack`.`estadoPublicacion` (`idEstadoPublicacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`comentario` (
  `idComentario` INT NOT NULL,
  `contenido` BLOB NULL,
  `fecha_publicacion` DATE NULL,
  `idPost` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idEstadoPublicacion` INT NOT NULL,
  `activo` TINYINT NULL,
  `colComentario` VARCHAR(45) NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_post1_idx` (`idPost` ASC) VISIBLE,
  INDEX `fk_usuario2_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_estadoPublicacion2_idx` (`idEstadoPublicacion` ASC) VISIBLE,
  CONSTRAINT `fk_post1`
    FOREIGN KEY (`idPost`)
    REFERENCES `foroFullstack`.`post` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario2`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `foroFullstack`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estadoPublicacion2`
    FOREIGN KEY (`idEstadoPublicacion`)
    REFERENCES `foroFullstack`.`estadoPublicacion` (`idEstadoPublicacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`valoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`valoracion` (
  `idValoracion` INT NOT NULL,
  `descripcionValoracion` VARCHAR(45) NULL,
  PRIMARY KEY (`idValoracion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`valoracionComentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`valoracionComentario` (
  `idValoracion` INT NOT NULL,
  `cantidad` INT NULL,
  `idComentario` INT NOT NULL,
  PRIMARY KEY (`idValoracion`, `idComentario`),
  INDEX `fk_valoracion3_idx` (`idValoracion` ASC) VISIBLE,
  INDEX `fk_comentario2_idx` (`idComentario` ASC) VISIBLE,
  CONSTRAINT `fk_valoracion3`
    FOREIGN KEY (`idValoracion`)
    REFERENCES `foroFullstack`.`valoracion` (`idValoracion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comentario2`
    FOREIGN KEY (`idComentario`)
    REFERENCES `foroFullstack`.`comentario` (`idComentario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`valoracionPost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`valoracionPost` (
  `idValoracion` INT NOT NULL,
  `idPost` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idValoracion`, `idPost`),
  INDEX `fk_post3_idx` (`idPost` ASC) VISIBLE,
  INDEX `fk_valoracion4_idx` (`idValoracion` ASC) VISIBLE,
  CONSTRAINT `fk_valoracion4`
    FOREIGN KEY (`idValoracion`)
    REFERENCES `foroFullstack`.`valoracion` (`idValoracion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post3`
    FOREIGN KEY (`idPost`)
    REFERENCES `foroFullstack`.`post` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`valoracionComentarioUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`valoracionComentarioUsuario` (
  `idValoracion` INT NOT NULL,
  `idComentario` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idValoracion`, `idComentario`, `idUsuario`),
  INDEX `fk_usuario3_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_valoracionComentario1_idx` (`idValoracion` ASC, `idComentario` ASC) VISIBLE,
  CONSTRAINT `fk_valoracionComentario1`
    FOREIGN KEY (`idValoracion` , `idComentario`)
    REFERENCES `foroFullstack`.`valoracionComentario` (`idValoracion` , `idComentario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario3`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `foroFullstack`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`valoracionPostUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`valoracionPostUsuario` (
  `idValoracion` INT NOT NULL,
  `idPost` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idValoracion`, `idPost`, `idUsuario`),
  INDEX `fk_usuario4_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_valoracionPost1_idx` (`idValoracion` ASC, `idPost` ASC) VISIBLE,
  CONSTRAINT `fk_valoracionPost1`
    FOREIGN KEY (`idValoracion` , `idPost`)
    REFERENCES `foroFullstack`.`valoracionPost` (`idValoracion` , `idPost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario4`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `foroFullstack`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`notificacion` (
  `idNotificacion` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idNotificacion`),
  INDEX `fk_usuario5_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario5`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `foroFullstack`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`notificacionPost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`notificacionPost` (
  `idNotificacion` INT NOT NULL,
  `idPost` INT NOT NULL,
  PRIMARY KEY (`idNotificacion`, `idPost`),
  INDEX `fk_post2_idx` (`idPost` ASC) VISIBLE,
  CONSTRAINT `fk_notificacion1`
    FOREIGN KEY (`idNotificacion`)
    REFERENCES `foroFullstack`.`notificacion` (`idNotificacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post2`
    FOREIGN KEY (`idPost`)
    REFERENCES `foroFullstack`.`post` (`idPost`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foroFullstack`.`notificacionComentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foroFullstack`.`notificacionComentario` (
  `idComentario` INT NOT NULL,
  `idNotificacion` INT NOT NULL,
  PRIMARY KEY (`idComentario`, `idNotificacion`),
  INDEX `fk_notificacion2_idx` (`idNotificacion` ASC) VISIBLE,
  CONSTRAINT `fk_comentario1`
    FOREIGN KEY (`idComentario`)
    REFERENCES `foroFullstack`.`comentario` (`idComentario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notificacion2`
    FOREIGN KEY (`idNotificacion`)
    REFERENCES `foroFullstack`.`notificacion` (`idNotificacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
